# Generated by Django 4.2 on 2023-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Archived', 'archived'), ('Sucsess', 'sucsess')], default='pending', max_length=8)),
            ],
        ),
    ]
